<?php

string_insert(null, null, STRING_LANG_PREFIX. "RU", "Russian", "EN");
string_insert(null, null, STRING_LANG_PREFIX. "EN", "English", "EN");
string_insert(null, null, "lang_is_changed", "Language changed", "EN");

String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Ball", "Balls", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Business-events", "Events for business", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Cinema", "Movies", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Circus", "Circus views", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Comedy-club", "Comedy Club", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Concert", "Concerts", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Dance-trainings", "Dance classes", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Discount", "Discounts", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Education", "Knowledge", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Evening", "Creative evenings", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Exhibition", "Exhibitions", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Fashion", "Fashion", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Festival", "Festivals", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Flashmob", "Flash mobs", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Games", "Games", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Global", "In the world", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Holiday", "Holidays", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Kids", "Baby", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Kvn", "KVN", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Magic", "Magicians, illusionists", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Masquerade", "Masquerades", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Meeting", "Meetings", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Night", "Night", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Open", "Open days", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Other", "Miscellaneous", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Party", "Parties", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Permanent-exhibitions", "Permanent exhibitions", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Photo", "photo events", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Presentation", "Presentations", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Quest", "Quests", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Romance", "Romance", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Sale", "Resale", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Shopping", "Shopping", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Show", "Show", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Social-activity", "Charity", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Speed-dating", "Quick Dating", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Sport", "Sports", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Stand-up", "Standup", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Stock", "Shares", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Theater", "Theater", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Tour", "Excursions", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Yarmarki-razvlecheniya-yarmarki", "Fairs", "EN");
String_insert (null, "web", STRING_EVENT_TYPE_NAME_PREFIX. "Yoga", "Yoga", "EN");

string_insert(null, null, "ban", "Your banned", "EN");

string_insert(null, null, STRING_SETTING_PREFIX. "Position", "Location", "EN");
string_insert(null, null, STRING_SETTING_PREFIX. "Privacy", "Filters", "EN");
string_insert(null, null, STRING_SETTING_PREFIX. "Notify", "Notifications", "EN");
string_insert(null, null, STRING_SETTING_PREFIX. "Lang", "Language", "EN");
string_insert(null, null, STRING_SETTING_PREFIX. "About", "About the program", "EN");
string_insert(null, null, STRING_SETTING_PREFIX. "Logout", "Exit", "EN");

string_insert(null, null, STRING_MENU_PREFIX. "Afisha", "Billboard", "EN");
string_insert(null, null, STRING_MENU_PREFIX. "Invites", "Invitations", "EN");
string_insert(null, null, STRING_MENU_PREFIX. "Map", "On the map", "EN");
string_insert(null, null, STRING_MENU_PREFIX. "Messages", "Messages", "EN");
string_insert(null, null, STRING_MENU_PREFIX. "Notify", "Notifications", "EN");
string_insert(null, null, STRING_MENU_PREFIX. "Support", "Help", "EN");
string_insert(null, null, STRING_MENU_PREFIX. "Settings", "Settings", "EN");
string_insert(null, "web", STRING_MENU_PREFIX. "Feedback", "Tasks", "EN");
string_insert(null, "web", STRING_MENU_PREFIX. "Event_new", "Add Event", "EN");
string_insert(null, "web", STRING_MENU_PREFIX. "Events_enable", "Enable events", "EN");
string_insert(null, "web", STRING_MENU_PREFIX. "Event_types", "Edit Invitations", "EN");


string_insert(null, null, "enable_gps_settings", "Open settings", "EN");
string_insert(null, null, "enable_gps", "Enable GPS", "EN");
string_insert(null, null, "repeat_login", "Re-enter", "EN");
string_insert(null, null, "check_internet", "Check your internet connection and try again", "EN");
string_insert(null, null, "login_to_server", "Login ...", "EN");
string_insert(null, null, "upload_from_gallery", "From gallery", "EN");
string_insert(null, null, "upload_from_camera", "Make photo", "EN");
string_insert(null, null, "email_is_busy", "Email busy", "EN");
string_insert(null, null, "second_name", "last name", "EN");
string_insert(null, null, "first_name", "Name", "EN");
string_insert(null, null, "password", "Password", "EN");
string_insert(null, null, "password_agin", "Repeat password", "EN");
string_insert(null, null, "password_not_equals", "Passwords do not match", "EN");
string_insert(null, null, "sex_invalid", "Gender not selected", "EN");
string_insert(null, null, "set_bdate", "Specify your birthday", "EN");
string_insert(null, null, "email_invalid", "Email entered incorrectly", "EN");
string_insert(null, null, "pass_invalid", "Password not filled", "EN");
string_insert(null, null, "email_or_pass_fail", "Email or Password entered incorrectly", "EN");
string_insert(null, null, "login", "Login", "EN");
string_insert(null, null, "registration", "Registration", "EN");
string_insert(null, null, "login_from_social_network", "or log in", "EN");
string_insert(null, null, "end_reg", "Register", "EN");
string_insert(null, null, "your_sex", "Your gender:", "EN");
string_insert(null, null, "sex_man", "Male", "EN");
string_insert(null, null, "sex_woman", "Female", "EN");
string_insert(null, null, "bdate", "Date of birth:", "EN");
string_insert(null, null, "online", "online", "EN");
string_insert(null, null, "old_online", "was online", "EN");
string_insert(null, null, "message_delete", "message deleted", "EN");
string_insert(null, null, "dialogs_is_not_exist", "No dialogs yet", "EN");
string_insert(null, null, "messages_reciever_profile", "Interlocutor profile", "EN");
string_insert(null, null, "add_to_black_list", "Add to black list", "EN");
string_insert(null, null, "remove_from_black_list", "Remove from blacklist", "EN");
string_insert(null, null, "messages_is_encripted", "Messages you send to this chat room are protected by encryption.", "EN");
string_insert(null, null, "message_readed", "Viewed", "EN");
string_insert(null, null, "copy_message", "Copy", "EN");
string_insert(null, null, "delete_message", "Delete", "EN");
string_insert(null, null, "message_is_copid", "Message copied", "EN");
string_insert(null, null, "message_is_deleted", "Message deleted", "EN");
string_insert(null, null, "dialog_lock", "User added to the black list", "EN");
string_insert(null, null, "dialog_unlock", "User deleted from blacklist", "EN");
string_insert(null, null, "dialog_banned", "Dialog blocked", "EN");
string_insert(null, null, "event_create", "Create", "EN");
string_insert(null, null, "all_dates", "No filter", "EN");
string_insert(null, null, "events_not_exist", "No invitations yet", "EN");
string_insert(null, null, "invite_friends_to_app", "Call Friends", "EN");
string_insert(null, null, "self_friends_not_exist", "You do not have any friends yet. You can invite them", "EN");
string_insert(null, null, "user_friends_not_exist", "No friends yet", "EN");
string_insert(null, null, "owner_likes_not_exist", "No hacks yet", "EN");
string_insert(null, null, "members_not_exist", "No Participants Yet", "EN");
string_insert(null, null, "app_repost_message", "I'll just leave it here", "EN");
string_insert(null, null, "you_invite_friends_in_app", "You invited friends", "EN");
string_insert(null, null, "owner_likes_title", "Profile hacks", "EN");
string_insert(null, null, "members_title", "Invites", "EN");
string_insert(null, null, "event_title", "Invitation", "EN");
string_insert(null, null, "kudago_all_event_types", "All categories", "EN");
string_insert(null, null, "kudago_events_not_exist", "There are no events yet", "EN");
string_insert(null, null, "kudago_event_title", "Event", "EN");
string_insert(null, null, "free", "FREE", "EN");
string_insert(null, null, "kudago_price", "Cost:", "EN");
string_insert(null, null, "event_unjoin", "I will not come", "EN");
string_insert(null, null, "event_joined", "You will go", "EN");
string_insert(null, null, "event_may_join", "Join", "EN");
string_insert(null, null, "event_settings", "Event customization", "EN");
string_insert(null, null, "event_update", "Edit", "EN");
string_insert(null, null, "event_delete", "Delete", "EN");
string_insert(null, null, "event_is_delete", "Event deleted", "EN");
string_insert(null, null, "event_is_not_delete", "The event has not been deleted, there are already members in it.", "EN");
string_insert(null, null, "event_join", "Join", "EN");
string_insert(null, null, "event_about", "Invitation Description", "EN");
string_insert(null, null, "time", "Time", "EN");
string_insert(null, null, "date", "Date", "EN");
string_insert(null, null, "enable_gps_and_find_coordinate", "Enable GPS or set the coordinates manually.", "EN");
string_insert(null, null, "find_coordinate", "Looking for coordinates, you can wait or set the coordinates manually.", "EN");
string_insert(null, null, "event_insert_loading_dialog", "Loading, please wait ...", "EN");
string_insert(null, null, "ok", "OK", "EN");
string_insert(null, null, "here", "here", "EN");
string_insert(null, null, "after_hour", "in an hour", "EN");
string_insert(null, null, "event_text", "description of the invitation", "EN");
string_insert(null, null, "more_events", "You have already created an invitation recently", "EN");
string_insert(null, null, "event_create_error", "Error, try again later.", "EN");
string_insert(null, null, "event_is_update", "Event changed", "EN");
string_insert(null, null, "event_is_not_update", "Edit Error", "EN");
string_insert(null, null, "finded_coordinate", "Coordinates are set", "EN");
string_insert(null, null, "image_upload_error", "Error loading image, please try again", "EN");
string_insert(null, null, "login_error", "Could not log in", "EN");
string_insert(null, null, "set_position_title", "Position Setting", "EN");
string_insert(null, null, "here_btn", "Right here", "EN");
string_insert(null, null, "meters", "m", "EN");
string_insert(null, null, "kilometers", "km", "EN");
string_insert(null, null, "year_11", "years", "EN");
string_insert(null, null, "year_12", "years", "EN");
string_insert(null, null, "year_13", "years", "EN");
string_insert(null, null, "year_14", "years", "EN");
string_insert(null, null, "year_x1", "year", "EN");
string_insert(null, null, "year_x2", "years", "EN");
string_insert(null, null, "year_x3", "years", "EN");
string_insert(null, null, "year_x4", "years", "EN");
string_insert(null, null, "year_xx", "years", "EN");

string_insert(null, null, "day_11", "days", "EN");
string_insert(null, null, "day_12", "days", "EN");
string_insert(null, null, "day_13", "days", "EN");
string_insert(null, null, "day_14", "days", "EN");
string_insert(null, null, "day_x1", "day", "EN");
string_insert(null, null, "day_x2", "days", "EN");
string_insert(null, null, "day_x3", "days", "EN");
string_insert(null, null, "day_x4", "day", "EN");
string_insert(null, null, "day_xx", "days", "EN");

string_insert(null, null, "hour_11", "hours", "EN");
string_insert(null, null, "hour_12", "hours", "EN");
string_insert(null, null, "hour_13", "hours", "EN");
string_insert(null, null, "hour_14", "hours", "EN");
string_insert(null, null, "hour_x1", "hour", "EN");
string_insert(null, null, "hour_x2", "hours", "EN");
string_insert(null, null, "hour_x3", "hours", "EN");
string_insert(null, null, "hour_x4", "hours", "EN");
string_insert(null, null, "hour_xx", "hours", "EN");

string_insert(null, null, "min_11", "minutes", "EN");
string_insert(null, null, "min_12", "minutes", "EN");
string_insert(null, null, "min_13", "minutes", "EN");
string_insert(null, null, "min_14", "minutes", "EN");
string_insert(null, null, "min_x1", "minute", "EN");
string_insert(null, null, "min_x2", "minutes", "EN");
string_insert(null, null, "min_x3", "minutes", "EN");
string_insert(null, null, "min_x4", "minutes", "EN");
string_insert(null, null, "min_xx", "minutes", "EN");

string_insert(null, null, "sec_11", "seconds", "EN");
string_insert(null, null, "sec_12", "seconds", "EN");
string_insert(null, null, "sec_13", "seconds", "EN");
string_insert(null, null, "sec_14", "seconds", "EN");
string_insert(null, null, "sec_x1", "second", "EN");
string_insert(null, null, "sec_x2", "seconds", "EN");
string_insert(null, null, "sec_x3", "seconds", "EN");
string_insert(null, null, "sec_x4", "seconds", "EN");
string_insert(null, null, "sec_xx", "seconds", "EN");

string_insert(null, null, "JANUARY", "January", "EN");
string_insert(null, null, "FEBRUARY", "February", "EN");
string_insert(null, null, "MARCH", "March", "EN");
string_insert(null, null, "APRIL", "April", "EN");
string_insert(null, null, "MAY", "May", "EN");
string_insert(null, null, "JUNE", "June", "EN");
string_insert(null, null, "JULY", "July", "EN");
string_insert(null, null, "AUGUST", "August", "EN");
string_insert(null, null, "SEPTEMBER", "September", "EN");
string_insert(null, null, "OCTOBER", "October", "EN");
string_insert(null, null, "NOVEMBER", "November", "EN");
string_insert(null, null, "DECEMBER", "December", "EN");


string_insert(null, null, "in_time", "in", "EN");
string_insert(null, null, "today_in", "today", "EN");
string_insert(null, null, "yesterday_in", "yesterday", "EN");
string_insert(null, null, "tomorrow_in", "tomorrow", "EN");
string_insert(null, null, "monday_in", "Monday", "EN");
string_insert(null, null, "tuesday_in", "Tuesday", "EN");
string_insert(null, null, "wednesday_in", "Wednesday", "EN");
string_insert(null, null, "trusday_in", "Thursday", "EN");
string_insert(null, null, "fryday_in", "Friday", "EN");
string_insert(null, null, "saturday_in", "Saturday", "EN");
string_insert(null, null, "sunday_in", "Sunday", "EN");


string_insert(null, null, "member_in", "Collected", "EN");
string_insert(null, null, "one_member", "member", "EN");
string_insert(null, null, "members", "member", "EN");
string_insert(null, null, "member", "members", "EN");
string_insert(null, null, "from", "of", "EN");
string_insert(null, null, "setting_position", "Location", "EN");
string_insert(null, null, "setting_notify", "Notifications", "EN");
string_insert(null, null, "setting_privacy", "Filters", "EN");
string_insert(null, null, "setting_lang", "Language", "EN");
string_insert(null, null, "setting_color", "Color", "EN");
string_insert(null, null, "setting_feedback", "Feedback", "EN");
string_insert(null, null, "setting_about", "About the program", "EN");
string_insert(null, null, "setting_exit", "Exit", "EN");
string_insert(null, null, "feedback_thanks", "Thank you for your feedback", "EN");
string_insert(null, null, "who_is_broken", "What would you change in the program?", "EN");
string_insert(null, null, "notify_not_exist", "No notifications yet", "EN");
string_insert(null, null, "message_insert_btn", "Message", "EN");
string_insert(null, null, "friend_insert_btn", "Add to friends", "EN");
string_insert(null, null, "member_joined_to_event", "Participant of the following events", "EN");


string_insert(null, null, "aries", "Aries", "EN");
string_insert(null, null, "taurus", "Taurus", "EN");
string_insert(null, null, "twins", "Twins", "EN");
string_insert(null, null, "cancer", "Cancer", "EN");
string_insert(null, null, "lion", "Lion", "EN");
string_insert(null, null, "virgin", "Virgo", "EN");
string_insert(null, null, "balance", "Libra", "EN");
string_insert(null, null, "scorpio", "Scorpion", "EN");
string_insert(null, null, "sagittarius", "Sagittarius", "EN");
string_insert(null, null, "capricorn", "Capricorn", "EN");
string_insert(null, null, "aquarius", "Aquarius", "EN");
string_insert(null, null, "fish", "Pisces", "EN");
string_insert(null, null, "friends_in_app", "friends in the application", "EN");
string_insert(null, null, "is_friend", "You are friends", "EN");
string_insert(null, null, "is_unjoined", "Wants to be invited", "EN");
string_insert(null, null, "friend_is_added", "User is added to friends", "EN");
string_insert(null, null, "dialogs_title", "Dialogs", "EN");
string_insert(null, null, "lang_is_changed", "Language changed", "EN");
string_insert(null, null, "event_filter_title", "Filters for the event", "EN");
string_insert(null, null, "event_filter_max_members", "Total Participants", "EN");
string_insert(null, null, "event_filter_boys", "Guys", "EN");
string_insert(null, null, "event_filter_girls", "Girls", "EN");
string_insert(null, null, "event_filter_years_from", "From", "EN");
string_insert(null, null, "event_filter_years", "years", "EN");
string_insert(null, null, "event_insert_filter", "filters", "EN");
string_insert(null, null, "kudago_child_event_insert", "Invite to event", "EN");
string_insert(null, "web", "locale_title", "Localization", "EN");
string_insert(null, "web", "event_type_insert_title", "Add invitation type", "EN");
string_insert(null, "web", "kudago_event_title", "Add event", "EN");
string_insert(null, "web", "select_first_value", "Select item", "EN");
string_insert(null, "web", "invite_to", "Invite to", "EN");
string_insert(null, "web", "invite_description", "Description", "EN");
string_insert(null, "web", "invite_price", "Price (optional)", "EN");
string_insert(null, "web", "invite_time", "Start date", "EN");
string_insert(null, "web", "invite_image", "Link to the icon", "EN");
string_insert(null, "web", "invite_image_load", "Upload image", "EN");
string_insert(null, "web", "invite_address", "Address", "EN");
string_insert(null, "web", "invite_address_placeholder", "Address not found", "EN");
string_insert(null, "web", "invite_address_set_button", "Specify address on map", "EN");
string_insert(null, "web", "invite_address_not_found", "Address not found", "EN");
string_insert(null, "web", "message_type_text", "Write message ...", "EN");
string_insert(null, "web", "message_send", "Send", "EN");
string_insert(null, "web", "children_events_exist", "Invitations to an event", "EN");
string_insert(null, "web", "children_events_not_exist", "You can invite people and go along with them", "EN");
string_insert(null, "web", "comments_exist", "comments", "EN");
string_insert(null, "web", "comments_not_exist", "No comments yet", "EN");
string_insert(null, "web", "invite_title", "Short description", "EN");
string_insert(null, "web", "invite_event_type", "Category", "EN");
string_insert(null, "web", "address_not_found", "Address not found", "EN");
string_insert(null, "web", "sex_any", "Girls and Guys", "EN");
string_insert(null, "web", "event_filter_member_to", "Before", "EN");
string_insert(null, "web", "event_filter_member_max", "people", "EN");
string_insert(null, "web", "invite_insert_button", "Invite", "EN");

string_insert(null, "web", "invite_position_is_empty", "Set the meeting point", "EN");
string_insert(null, "web", "invite_time_is_empty", "Set meeting time", "EN");
string_insert(null, "web", "invite_type_is_empty", "Set meeting category", "EN");
string_insert(null, "web", "invite_update_button", "Edit", "EN");
string_insert(null, "web", "tab_to_open", "Click to open the menu", "EN");
string_insert(null, "web", "member_joined_not_exist", "Not yet participated in events", "EN");
string_insert(null, "web", "select_all", "Enable all", "EN");
string_insert(null, "web", "deselect_all", "Disable all", "EN");
string_insert(null, "web", "event_type_list", "List of possible types of events", "EN");
string_insert(null, "web", "event_type_list_active", "Active event types", "EN");
string_insert(null, null, "invite_member_count", "invitations", "EN");
string_insert(null, "web", "add_event_type", "Add type of invitations", "EN");
string_insert(null, "web", "event_type_name", "Invitation Category", "EN");
string_insert(null, "web", "event_type_image", "Invitation icon", "EN");
string_insert(null, "web", "event_type_update", "Edit", "EN");
string_insert(null, "web", "event_type_visible", "visible", "EN");
string_insert(null, "web", "event_type_invisible", "Hidden", "EN");
string_insert(null, null, "event_insert_image_insert", "add photo", "EN");
string_insert(null, null, "event_insert_image_update", "change photo", "EN");
string_insert(null, null, "update", "Edit", "EN");
string_insert(null, null, "delete", "Delete", "EN");
string_insert(null, null, "event_insert_set_position", "meeting place", "EN");
string_insert(null, "web", "event_type_insert_name_not_exist", "Invitation category is not full", "EN");

string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "10", "Critical error", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "20", "Error 5 complexity", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "21", "Error 4 complexity", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "22", "Error 3 complexity", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "23", "Error 2 complexity", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "24", "Error 1 complexity", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "30", "Pending evaluation", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "50", "Task 5 complexity", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "51", "Task 4 of complexity", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "52", "Task 3 of complexity", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "53", "Task 2 of complexity", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "54", "Task 1 of complexity", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "90", "Implemented", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "91", "Tested", "EN");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX. "100", "In the archive", "EN");

string_insert(null, null, "invite_like", "I rated your invitation", "EN");
string_insert(null, null, "owner_like", "Estimate your profile", "EN");
string_insert(null, null, "owner_invited", "Invited by", "EN");
string_insert(null, null, "invite_join", "Joined the event", "EN");
string_insert(null, null, "comment_insert", "Leave a comment", "EN");

string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX. PUSH_TYPE_INVITE_COMMENT_INSERT, "Comments", "EN");
string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX. PUSH_TYPE_MESSAGE_INSERT, "Messages", "EN");
string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX. PUSH_TYPE_INVITE_INVITED, "Invitations", "EN");
string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX. PUSH_TYPE_LIKE_INVITE, "Event hacks", "EN");
string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX. PUSH_TYPE_LIKE_OWNER, "Profile hacks", "EN");
string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX. PUSH_TYPE_INVITE_JOIN, "Participant joined", "EN");
string_insert(null, null, "push_visible_is_set", "Setting is set", "EN");

string_insert(null, null, "current_position", "Current location", "EN");
string_insert(null, null, "face_position", "Other location", "EN");
string_insert(null, null, "image_error", "Error loading photos", "EN");
string_insert(null, null, "image_uploading", "image loading ...", "EN");
string_insert(null, null, "image_update", "change photo", "EN");
string_insert(null, null, "image_insert", "add photo", "EN");
string_insert(null, "web", "invite_image_is_empty", "Upload image", "EN");
string_insert(null, null, "event_created", "Event created", "EN");
string_insert(null, null, "invite_title_is_empty", "Title is empty", "EN");
string_insert(null, null, "forgot_password", "forgot password", "EN");
string_insert(null, null, "forgot_button", "Send password to email", "EN");
string_insert(null, null, "restore_mail_title", "Password recovery", "EN");
string_insert(null, null, "restore_mail_click_to_link", "Follow the link to reset your password", "EN");
string_insert(null, null, "change_password", "Change password", "EN");
string_insert(null, null, "new_password", "New password", "EN");
string_insert(null, null, "restore_mail_send", "Check your mail", "EN");
