<?php


string_insert(null, null, STRING_LANG_PREFIX . "RU", "Русский");
string_insert(null, null, STRING_LANG_PREFIX . "EN", "Английский");
string_insert(null, null, "lang_is_changed", "Язык изменен");


string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "ball", "Балы");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "business-events", "События для бизнеса");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "cinema", "Кино");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "circus", "Цирковые представления");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "comedy-club", "Камеди клаб");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "concert",  "Концерты");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "dance-trainings", "Занятия танцами");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "discount",  "Скидки");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "education", "Знания");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "evening", "Творческие вечера");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "exhibition",   "Выставки");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "fashion", "Мода");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "festival", "Фестивали");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "flashmob", "Флешмобы");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "games", "Игры");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "global", "В мире");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "holiday",  "Праздники");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "kids", "Детские");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "kvn",  "КВН");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "magic", "Фокусники, иллюзионисты");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "masquerade", "Маскарады");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "meeting", "Встречи");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "night", "Ночь");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "open", "Дни открытых дверей");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "other", "Разное");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "party", "Вечеринки");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "permanent-exhibitions", "Постоянные выставки");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "photo", "Фотособытия");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "presentation", "Презентации");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "quest", "Квесты");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "romance", "Романтика");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "sale", "Распродажа");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "shopping", "Шопинг");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "show", "Шоу");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "social-activity", "Благотворительность");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "speed-dating", "Быстрые свидания");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "sport", "Спорт");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "stand-up", "Стендап");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "stock", "Акции");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "theater", "Театр");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "tour", "Экскурсии");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "yarmarki-razvlecheniya-yarmarki", "Ярмарки");
string_insert(null, "web", STRING_EVENT_TYPE_NAME_PREFIX . "yoga", "Йога");

string_insert(null, null, "ban", "Вы забанены");

string_insert(null, null, STRING_SETTING_PREFIX . "position", "Местоположение");
string_insert(null, null, STRING_SETTING_PREFIX . "privacy", "Фильтры");
string_insert(null, null, STRING_SETTING_PREFIX . "notify", "Уведомления");
string_insert(null, null, STRING_SETTING_PREFIX . "lang", "Язык");
string_insert(null, null, STRING_SETTING_PREFIX . "about", "О программе");
string_insert(null, null, STRING_SETTING_PREFIX . "logout", "Выход");

string_insert(null, null, STRING_MENU_PREFIX . "afisha", "Афиша");
string_insert(null, null, "w", "Мои приглашения");
string_insert(null, null, STRING_MENU_PREFIX . "invites", "Приглашения");
string_insert(null, null, STRING_MENU_PREFIX . "map", "На карте");
string_insert(null, null, STRING_MENU_PREFIX . "dialogs", "Сообщения");
string_insert(null, null, STRING_MENU_PREFIX . "notifies", "Уведомления");
string_insert(null, null, STRING_MENU_PREFIX . "support", "Помощь");
string_insert(null, null, STRING_MENU_PREFIX . "settings", "Настройки");
string_insert(null, "web", STRING_MENU_PREFIX . "feedback", "Задачи");
string_insert(null, "web", STRING_MENU_PREFIX . "apps_update", "Регистрация приложений");
string_insert(null, "web", STRING_MENU_PREFIX . "download_android", "Скачать приложение");
string_insert(null, "web", STRING_MENU_PREFIX . "app_settings", "Настройки приложения");
string_insert(null, "web", STRING_MENU_PREFIX . "app_settings", "Настройки приложения");
string_insert(null, "web", "app_settings_basic", "Основные настройки");
string_insert(null, "web", "event_new", "Добавить мероприятие");
string_insert(null, "web", "events_enable", "Включить мероприятия");
string_insert(null, "web", "event_types", "Изменить приглашения");
string_insert(null, null, "start_test", "Тест для входа в приложение");
string_insert(null, null, "test_need", "Необходимо пройти тест для того что бы получить доступ к приложению.");
string_insert(null, null, "start", "Старт");
string_insert(null, "web", "enable_start_test_checkbox", "Проходить тест при входе в приложение");
string_insert(null, "web", "test_question_count_caption", "Количество вопросов в тесте");
string_insert(null, "web", "tests_language", "Язык тестов");
string_insert(null, "web", "test_question", "Вопрос");
string_insert(null, "web", "test_true_value", "Правильный ответ");
string_insert(null, "web", "test_false_value", "Неверный ответ");
string_insert(null, "web", "test_false_value", "Неверный ответ");
string_insert(null, null, "test_next", "Следующий");
string_insert(null, null, "test_results", "Результат тестирования");
string_insert(null, null, "test_completed_success", "Тест пройден успешно");
string_insert(null, null, "test_completed_fail", "Тест не пройден.
Вам закрыт доступ к приложению.");

string_insert(null, null, "enable_gps_settings", "Открыть настройки");
string_insert(null, null, "enable_gps", "Включите GPS");
string_insert(null, null, "repeat_login", "Повторить вход");
string_insert(null, null, "check_internet", "Проверьте подключение к интернету и повторите попытку");
string_insert(null, null, "login_to_server", "Вход ...");
string_insert(null, null, "upload_from_gallery", "Из галереи");
string_insert(null, null, "upload_from_camera", "Сделать фото");
string_insert(null, null, "email_is_busy", "Email занят");
string_insert(null, null, "second_name", "Фамилия");
string_insert(null, null, "first_name", "Имя");
string_insert(null, null, "password", "Пароль");
string_insert(null, null, "password_agin", "Повторите пароль");
string_insert(null, null, "password_not_equals", "Пароли не совпадают");
string_insert(null, null, "sex_invalid", "Пол не выбран");
string_insert(null, null, "set_bdate", "Укажите свой день рождения");
string_insert(null, null, "email_invalid", "Email введен неверно");
string_insert(null, null, "pass_invalid", "Пароль не заполнен");
string_insert(null, null, "email_or_pass_fail", "Email или Пароль введен неверно");
string_insert(null, null, "login", "Вход");
string_insert(null, null, "registration", "Регистрация");
string_insert(null, null, "login_from_social_network", "или войти через");
string_insert(null, null, "end_reg", "Зарегистрироваться");
string_insert(null, null, "your_sex", "Ваш пол:");
string_insert(null, null, "sex_man", "Мужской");
string_insert(null, null, "sex_woman", "Женский");
string_insert(null, null, "bdate", "Дата рождения:");
string_insert(null, null, "online", "online");
string_insert(null, null, "old_online", "был в сети");
string_insert(null, null, "message_delete", "сообщение удалено");
string_insert(null, null, "dialogs_is_not_exist", "Диалогов пока нет");
string_insert(null, null, "messages_reciever_profile", "Профиль собеседника");
string_insert(null, null, "add_to_black_list", "Добавить в черный список");
string_insert(null, null, "remove_from_black_list", "Удалить из черного списка");
string_insert(null, null, "messages_is_encripted", "Сообщения, которые вы отправляете в данный чат, защищены шифрованием.");
string_insert(null, null, "message_readed", "Просмотрено");
string_insert(null, null, "copy_message", "Копировать");
string_insert(null, null, "delete_message", "Удалить");
string_insert(null, null, "message_is_copid", "Сообщение скопировано");
string_insert(null, null, "message_is_deleted", "Сообщение удалено");
string_insert(null, null, "dialog_lock", "Пользователь добавлен в черный список");
string_insert(null, null, "dialog_unlock", "Пользователь удален из черного списка");
string_insert(null, null, "dialog_banned", "Диалог заблокирован");
string_insert(null, null, "event_create", "Создать");
string_insert(null, null, "all_dates", "Без фильтра");
string_insert(null, null, "events_not_exist", "Пока приглашений нет");
string_insert(null, null, "invite_friends_to_app", "Позвать друзей");
string_insert(null, null, "self_friends_not_exist", "У вас пока нет друзей. Вы можете их пригласить");
string_insert(null, null, "user_friends_not_exist", "Друзей пока нет");
string_insert(null, null, "owner_likes_not_exist", "Лайков пока нет");
string_insert(null, null, "members_not_exist", "Участников пока нет");
string_insert(null, null, "app_repost_message", "Я просто оставлю это сдесь");
string_insert(null, null, "you_invite_friends_in_app", "Вы пригласили друзей");

string_insert(null, null, "owner_likes_title", "Лайки профиля");
string_insert(null, null, "members_title", "Приглашенные");
string_insert(null, null, "event_title", "Приглашение");
string_insert(null, null, "kudago_all_event_types", "Все категории");
string_insert(null, null, "kudago_events_not_exist", "Пока мероприятий нет");
string_insert(null, null, "kudago_event_title", "Мероприятие");
string_insert(null, null, "free", "БЕСПЛАТНО");
string_insert(null, null, "kudago_price", "Стоимость:");
string_insert(null, null, "event_unjoin", "Я не приду");
string_insert(null, null, "event_joined", "Вы пойдете");
string_insert(null, null, "event_may_join", "Присоединиться");
string_insert(null, null, "event_settings", "Настройка события");
string_insert(null, null, "event_update", "Редактировать");
string_insert(null, null, "event_delete", "Удалить");
string_insert(null, null, "event_is_delete", "Событие удалено");
string_insert(null, null, "event_is_not_delete", "Событие не удалено. В нем уже есть участники.");
string_insert(null, null, "event_join", "Присоединиться");
string_insert(null, null, "event_about", "Описание приглашения");
string_insert(null, null, "time", "Время");
string_insert(null, null, "date", "Дата");
string_insert(null, null, "enable_gps_and_find_coordinate", "Включите GPS или устанавите координаты вручную.");
string_insert(null, null, "find_coordinate", "Ищем координаты, можете подождать или устанавить координаты вручную.");
string_insert(null, null, "event_insert_loading_dialog", "Загрузка, подождите пожалуйста...");
string_insert(null, null, "ok", "OK");
string_insert(null, null, "here", "здесь");
string_insert(null, null, "after_hour", "через час");
string_insert(null, null, "event_text", "описание приглашения");
string_insert(null, null, "more_events", "Вы недавно уже создали приглашение");
string_insert(null, null, "event_create_error", "Ошибка. Повторите запрос позже.");
string_insert(null, null, "event_is_update", "Событие изменено");
string_insert(null, null, "event_is_not_update", "Ошибка редактирования");
string_insert(null, null, "finded_coordinate", "Координаты установлены");
string_insert(null, null, "image_upload_error", "Ошибка загрузки изображения. Повторите загрузку");
string_insert(null, null, "login_error", "Не получилось войти");
string_insert(null, null, "set_position_title", "Установка позиции");
string_insert(null, null, "here_btn", "Прямо тут");
string_insert(null, null, "meters", "м");
string_insert(null, null, "kilometers", "км");


string_insert(null, null, "year_11", "лет");
string_insert(null, null, "year_12", "лет");
string_insert(null, null, "year_13", "лет");
string_insert(null, null, "year_14", "лет");
string_insert(null, null, "year_x1", "год");
string_insert(null, null, "year_x2", "года");
string_insert(null, null, "year_x3", "года");
string_insert(null, null, "year_x4", "года");
string_insert(null, null, "year_xx", "лет");

string_insert(null, null, "day_11", "дней");
string_insert(null, null, "day_12", "дней");
string_insert(null, null, "day_13", "дней");
string_insert(null, null, "day_14", "дней");
string_insert(null, null, "day_x1", "день");
string_insert(null, null, "day_x2", "дня");
string_insert(null, null, "day_x3", "дня");
string_insert(null, null, "day_x4", "дня");
string_insert(null, null, "day_xx", "дней");

string_insert(null, null, "hour_11", "часов");
string_insert(null, null, "hour_12", "часов");
string_insert(null, null, "hour_13", "часов");
string_insert(null, null, "hour_14", "часов");
string_insert(null, null, "hour_x1", "час");
string_insert(null, null, "hour_x2", "часа");
string_insert(null, null, "hour_x3", "часа");
string_insert(null, null, "hour_x4", "часа");
string_insert(null, null, "hour_xx", "часов");

string_insert(null, null, "min_11", "минут");
string_insert(null, null, "min_12", "минут");
string_insert(null, null, "min_13", "минут");
string_insert(null, null, "min_14", "минут");
string_insert(null, null, "min_x1", "минуту");
string_insert(null, null, "min_x2", "минуты");
string_insert(null, null, "min_x3", "минуты");
string_insert(null, null, "min_x4", "минуты");
string_insert(null, null, "min_xx", "минут");

string_insert(null, null, "sec_11", "секунд");
string_insert(null, null, "sec_12", "секунд");
string_insert(null, null, "sec_13", "секунд");
string_insert(null, null, "sec_14", "секунд");
string_insert(null, null, "sec_x1", "секунду");
string_insert(null, null, "sec_x2", "секунды");
string_insert(null, null, "sec_x3", "секунды");
string_insert(null, null, "sec_x4", "секунды");
string_insert(null, null, "sec_xx", "секунд");

string_insert(null, null, "JANUARY", "января");
string_insert(null, null, "FEBRUARY", "февраля");
string_insert(null, null, "MARCH", "марта");
string_insert(null, null, "APRIL", "апреля");
string_insert(null, null, "MAY", "мая");
string_insert(null, null, "JUNE", "июня");
string_insert(null, null, "JULY", "июля");
string_insert(null, null, "AUGUST", "августа");
string_insert(null, null, "SEPTEMBER", "сентября");
string_insert(null, null, "OCTOBER", "октября");
string_insert(null, null, "NOVEMBER", "ноября");
string_insert(null, null, "DECEMBER", "декабря");


string_insert(null, null, "in_time", "в");
string_insert(null, null, "today_in", "сегодня");
string_insert(null, null, "yesterday_in", "вчера");
string_insert(null, null, "tomorrow_in", "завтра");
string_insert(null, null, "monday_in", "в понедельник");
string_insert(null, null, "tuesday_in", "во вторник");
string_insert(null, null, "wednesday_in", "в среду");
string_insert(null, null, "trusday_in", "в четверг");
string_insert(null, null, "fryday_in", "в пятницу");
string_insert(null, null, "saturday_in", "в субботу");
string_insert(null, null, "sunday_in", "в воскресенье");


string_insert(null, null, "member_in", "Собрались");
string_insert(null, null, "one_member", "участник");
string_insert(null, null, "members", "участника");
string_insert(null, null, "member", "участников");
string_insert(null, null, "from", "из");
string_insert(null, null, "setting_position", "Местоположение");
string_insert(null, null, "setting_notify", "Уведомления");
string_insert(null, null, "setting_privacy", "Фильтры");
string_insert(null, null, "setting_lang", "Язык");
string_insert(null, null, "setting_color", "Цвет");
string_insert(null, null, "setting_feedback", "Отзыв");
string_insert(null, null, "setting_about", "О программе");
string_insert(null, null, "setting_exit", "Выход");
string_insert(null, null, "feedback_thanks", "Спасибо за ваш отзыв");
string_insert(null, null, "who_is_broken", "Что бы вы поменяли в программе?");
string_insert(null, null, "notify_not_exist", "Уведомлений пока нет");
string_insert(null, null, "message_insert_btn", "Сообщение");
string_insert(null, null, "friend_insert_btn", "Добавить в друзья");
string_insert(null, null, "member_joined_to_event", "Участник следующих событий");


string_insert(null, null, "aries", "Овен");
string_insert(null, null, "taurus", "Телец");
string_insert(null, null, "twins", "Близнецы");
string_insert(null, null, "cancer", "Рак");
string_insert(null, null, "lion", "Лев");
string_insert(null, null, "virgin", "Дева");
string_insert(null, null, "balance", "Весы");
string_insert(null, null, "scorpio", "Скорпион");
string_insert(null, null, "sagittarius", "Стрелец");
string_insert(null, null, "capricorn", "Козерог");
string_insert(null, null, "aquarius", "Водолей");
string_insert(null, null, "fish", "Рыбы");
string_insert(null, null, "friends_in_app", "друзей в приложении");
string_insert(null, null, "is_friend", "У вас в друзьях");
string_insert(null, null, "is_unjoined", "Хочет что бы его пригласили");
string_insert(null, null, "friend_is_added", "Пользователь добавлен в список друзей");
string_insert(null, null, "dialogs_title", "Диалоги");
string_insert(null, null, "lang_is_changed", "Язык изменен");
string_insert(null, null, "event_filter_title", "Фильтры для события");
string_insert(null, null, "event_filter_max_members", "Всего участников");
string_insert(null, null, "event_filter_boys", "Парни");
string_insert(null, null, "event_filter_girls", "Девушки");
string_insert(null, null, "event_filter_years_from", "От");
string_insert(null, null, "event_filter_years", "лет");
string_insert(null, null, "event_insert_filter", "фильтры");
string_insert(null, null, "kudago_child_event_insert", "Пригласить на мероприятие");


string_insert(null, "web", "locale_title", "Локализация");
string_insert(null, "web", "event_type_insert_title", "Добавить тип приглашения");
string_insert(null, "web", "kudago_event_title", "Добавить мероприятие");
string_insert(null, "web", "select_first_value", "Выберите пункт");
string_insert(null, "web", "invite_to", "Пригласить на");
string_insert(null, "web", "invite_description", "Описание");
string_insert(null, "web", "invite_price", "Цена (необязательно заполнять)");
string_insert(null, "web", "invite_time", "Дата начала");
string_insert(null, "web", "invite_image", "Ссылка на иконку");
string_insert(null, "web", "invite_image_load", "Загрузить картинку");
string_insert(null, "web", "invite_address", "Адрес");
string_insert(null, "web", "invite_address_placeholder", "Адрес не найден");
string_insert(null, "web", "invite_address_set_button", "Указать адрес на карте");
string_insert(null, "web", "invite_address_not_found", "Не найден адрес");
string_insert(null, "web", "message_type_text", "Напишите сообщение ...");
string_insert(null, "web", "message_send", "Отправить");
string_insert(null, "web", "children_events_exist", "Приглашения на мероприятие");
string_insert(null, "web", "children_events_not_exist", "Вы можете пригласить людей и пойти вместе с ними");
string_insert(null, "web", "comments_exist", "комментариев");
string_insert(null, "web", "comments_not_exist", "Комментариев пока нет");
string_insert(null, "web", "invite_title", "Краткое описание");
string_insert(null, "web", "invite_event_type", "Категория");
string_insert(null, "web", "address_not_found", "Адрес не найден");
string_insert(null, "web", "sex_any", "Девушки и Парни");
string_insert(null, "web", "event_filter_member_to", "Макс");
string_insert(null, "web", "event_filter_member_max", "чел");
string_insert(null, null, "invite_insert_button", "Пригласить");
string_insert(null, null, "invite_update_button", "Пригласить");

string_insert(null, "web", "invite_position_is_empty", "Установите место встречи");
string_insert(null, "web", "invite_time_is_empty", "Установите время встречи");
string_insert(null, "web", "invite_type_is_empty", "Установите категорию встречи");
string_insert(null, "web", "invite_update_button", "Изменить");
string_insert(null, "web", "tab_to_open", "Нажмите что бы открыть меню");
string_insert(null, "web", "member_joined_not_exist", "Пока не учавствовал в событиях");
string_insert(null, "web", "select_all", "Включить все");
string_insert(null, "web", "deselect_all", "Выключить все");
string_insert(null, "web", "event_type_list", "Список возможных типов событий");
string_insert(null, "web", "event_type_list_active", "Активные типы событий");
string_insert(null, null, "invite_member_count", "приглашений");
string_insert(null, "web", "add_event_type", "Добавить тип приглашений");
string_insert(null, "web", "event_type_name", "Категория приглашения");
string_insert(null, "web", "event_type_image", "Иконка приглашения");
string_insert(null, "web", "event_type_update", "Изменить");
string_insert(null, "web", "event_type_visible", "Виден");
string_insert(null, "web", "event_type_invisible", "Скрыт");
string_insert(null, null, "event_insert_image_insert", "добавить фото");
string_insert(null, null, "event_insert_image_update", "изменить фото");
string_insert(null, null, "settings", "Настройки");
string_insert(null, null, "save", "Сохранить");
string_insert(null, null, "update", "Изменить");
string_insert(null, null, "delete", "Удалить");
string_insert(null, null, "event_insert_set_position", "место встречи");
string_insert(null, "web", "event_type_insert_name_not_exist", "Категория приглашения не заполнена");


string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "10", "Критическая ошибка");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "20", "Ошибка 5 сложности");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "21", "Ошибка 4 сложности");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "22", "Ошибка 3 сложности");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "23", "Ошибка 2 сложности");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "24", "Ошибка 1 сложности");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "30", "Ожидает оценки");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "50", "Задача 5 сложности");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "51", "Задача 4 сложности");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "52", "Задача 3 сложности");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "53", "Задача 2 сложности");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "54", "Задача 1 сложности");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "90", "Реализован");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "91", "Протестирован");
string_insert(null, "web", STRING_FEEDBACK_STATUS_PREFIX . "100", "В архиве");

string_insert(null, null, "invite_like", "Оценил ваше приглашение");
string_insert(null, null, "owner_like", "Оценил ваш профиль");
string_insert(null, null, "owner_invited", "Пригласил на ");
string_insert(null, null, "invite_join", "Присоединился к мероприятию");
string_insert(null, null, "comment_insert", "Оставил комментарий");

string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX . PUSH_TYPE_INVITE_COMMENT_INSERT, "Комментарии");
string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX . PUSH_TYPE_MESSAGE_INSERT, "Сообщения");
string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX . PUSH_TYPE_INVITE_INVITED, "Приглашения");
string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX . PUSH_TYPE_LIKE_INVITE, "Лайки событий");
string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX . PUSH_TYPE_LIKE_OWNER, "Лайки профиля");
string_insert(null, null, PUSH_TYPE_SETTING_NAME_PREFIX . PUSH_TYPE_INVITE_JOIN, "Присоединился участник");
string_insert(null, null, "push_visible_is_set", "Настройка установлена");

string_insert(null, null, "current_position", "Текущее местоположение");
string_insert(null, null, "face_position", "Другое местоположение");
string_insert(null, null, "image_error", "Ошибка загрузки фотографии");
string_insert(null, null, "image_uploading", "загружка изображения...");
string_insert(null, null, "image_update", "изменить фотографию");
string_insert(null, null, "image_insert", "добавить фотографию");
string_insert(null, "web", "invite_image_is_empty", "Загрузите изображение");
string_insert(null, null, "event_created", "Создано событие");
string_insert(null, null, "invite_title_is_empty", "Заполните краткое описание");
string_insert(null, null, "forgot_password", "забыл пароль");
string_insert(null, null, "forgot_button", "Отправить пароль на емайл");
string_insert(null, null, "restore_mail_title", "Восстановление пароля");
string_insert(null, null, "restore_mail_click_to_link", "Перейдите по ссылке для сброса пароля");
string_insert(null, null, "change_password", "Изменить пароль");
string_insert(null, null, "new_password", "Новый пароль");
string_insert(null, null, "restore_mail_send", "Проверьте почту");
string_insert(null, null, "password_changed", "Пароль изменен");
string_insert(null, null, "restore_token_is_bad", "Ссылка устарела. Пройдите процедуру восстановления пароля заново");
string_insert(null, null, "login_or_password_is_bad", "Логин или пароль введен неверно");
string_insert(null, null, "login_mail_title", "Добро пожаловать");
string_insert(null, null, "login_mail_body", "Мы приветствуем вас на на нашем ресурсе");



string_insert(null, null, "email_from_name", "Администрация");
string_insert(null, null, "mail_support_title", "Поступило сообщение в раздел помощь.");

string_insert(null, null, "app_name_caption", "Название приложения");
string_insert(null, null, "app_description_caption", "Описание в Google Play");
string_insert(null, null, "owner_distance_caption", "Расстояние до границы видимых событий (метров)");
string_insert(null, null, "visible_event_interval_after_event_time_caption", "Время до скрытия события после начала (минут)");
string_insert(null, null, "app_logo_caption", "Логотип приложения");
string_insert(null, null, "avatar_placeholder_caption", "Аватар пользователей зарегистрировавшихся через email");
string_insert(null, null, "image_placeholder_caption", "Изображение по умолчанию для категорий мероприятий");

string_insert(null, null, "mail_contacts_title", "Обратная связь");
string_insert(null, null, "mail_app_insert_title", "Заявка принята");
string_insert(null, null, "mail_pay_success_title", "Платеж получен");
string_insert(null, null, "mail_app_uploaded_title", "Приложение загружено в Google Play");
string_insert(null, null, STRING_EVENT_TYPE_NAME_PREFIX . "meet", "Встреча");
string_insert(null, null, "search_address", "Поиск адреса");
string_insert(null, null, "date_filter", "Фильтр даты");
string_insert(null, null, "recommended", "Рекомендуем");
string_insert(null, null, "open_web_app", "Открыть сайт");
string_insert(null, null, "download_android_app", "Скачать Android приложение");
string_insert(null, null, "event_copy_link", "Копировать ссылку");
string_insert(null, null, "link_is_copy", "Ссылка скопирована");

string_insert(null, "web", "new_messages", "Новые сообщения");
string_insert(null, null, "new_notify", "новое");
